### ISSUE TITLE
Error on C1M5L3_Code_Reuse_V2

### ISSUE THREAD

**Issue by thedarshanjadhav** [fkhjoy/Coursera-Crash-Course-on-Python#19]
In turtle class its showing again and again that.. name 'Animal' is not defined ..

**Comment by fkhjoy** [comment]
did you run your `class Animal:` cell

**Comment by thedarshanjadhav** [comment]
Now it's working fine.. thankyou sir for your response

**Comment by fkhjoy** [comment]
you are welcome
