### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by amirbejaoui** [fkhjoy/Coursera-Crash-Course-on-Python#5]
Hey, I'm new to github and programming in general. I have been taking the crash course on python by google and your work has already helped me so much. Thank you for that.
I would like to do the same thing as you, as many of problems presented in the course have changed, and also I would like to have my work saved neatly like yours. Can you help me through some instructions on how you did yours?

**Comment by fkhjoy** [comment]
You have to learn to use git. Go through some tutorials on it. 
Take a look on these [git - the simple guide](http://rogerdudler.github.io/git-guide/) and [Basic Git Command Line Reference for Windows Users](http://johnatten.com/2012/09/08/basic-git-command-line-reference-for-windows-users/#BASH-REMOTE-REPOSITORIES) . If you need any further help, E-mail me to khjoyfoysal@gmail.com
