### ISSUE TITLE
NameError: name 'file_contents' is not defined

### ISSUE THREAD

**Issue by achalofficial** [fkhjoy/Coursera-Crash-Course-on-Python#6]
In the Final Project, it shows this error. Help me with this

**Comment by fkhjoy** [comment]
Did you upload your .txt file?

**Comment by achalofficial** [comment]
Which Txt do I need to Upload ?

**Comment by achalofficial** [comment]
and where I need to upload it ??

**Comment by fkhjoy** [comment]
![image](https://user-images.githubusercontent.com/25137428/81909211-124bcf00-95ec-11ea-8c29-f68bca07df13.png)
Here

**Comment by achalofficial** [comment]
I still can recognize how to do it ?? 
How to upload this file

**Comment by achalofficial** [comment]
I still cant recognize how to upload it ??

**Comment by achalofficial** [comment]
![Screenshot 2020-05-15 at 9 24 05 PM](https://user-images.githubusercontent.com/61355241/82070480-6d67e980-96f2-11ea-87da-303cc02cb5e8.png)

This is the Error I am Getting

**Comment by fkhjoy** [comment]
Restart the Kernel. Try again.
