### ISSUE TITLE
NameError: name 'file_contents' is not defined #6

### ISSUE THREAD

**Issue by devinav** [fkhjoy/Coursera-Crash-Course-on-Python#8]

**Comment by devinav** [comment]
can you please with this?

**Comment by fkhjoy** [comment]
Your .txt file wasn't uploaded properly.
Restart the kernel from Kernel menu and run again.
You have to be able to upload the .txt file for word cloud.
Let me know if it helped you

**Comment by devinav** [comment]
Ok thanks
